### PR TITLE
fix: disks stats for windows

### PR DESCRIPTION
**Pull request by NoPlagiarism**
## Description

Disables disk filtering for Windows

Mentioned in #40

## Type of change

Bug fix

## Tests

- [ ] Before merging test it on Linux

## Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my code
- My changes generate no new warnings

### CODE REVIEW

**Comment by NoPlagiarism** [comment]
Sorry for that

**Comment by Abdenasser** [comment]
> Sorry for that

no worries, thank you!

**Comment by Abdenasser** [comment]
@NoPlagiarism would you like to address the following

```shell
error[E0308]: mismatched types
  --> src/main.rs:83:5
   |
82 |   fn filter_disks(disks: &[Disk]) -> Iter<Disk> {
   |                                      ---------- expected `std::slice::Iter<'_, sysinfo::Disk>` because of return type
83 | /     disks.iter().filter(|disk| {
84 | |         // Filter for physical disks - typically those mounted at "/"
85 | |         disk.mount_point() == std::path::Path::new("/")
86 | |     })
   | |______^ expected `Iter<'_, Disk>`, found `Filter<Iter<'_, Disk>, ...>`
   |
   = note: expected struct `std::slice::Iter<'_, _>`
              found struct `Filter<std::slice::Iter<'_, _>, {closure@src/main.rs:83:25: 83:31}>`
For more information about this error, try `rustc --explain E0308`.
error: could not compile `macos-task-manager` (bin "macos-task-manager") due to 1 previous error
failed to build app: failed to build app
    Error failed to build app: failed to build app
Error: Process completed with exit code 1.
```

**Review by Abdenasser — APPROVED** [review]
lgtm, thank you!

**Comment by NoPlagiarism** [comment]
Thanks for fixing it

**Pull request merged**
