### PR TITLE
fix: links not opening at all

### PR DESCRIPTION
**Pull request by back2Lobby**
## Description

No link was opening in the app. This pr adds the tauri shell plugin that will allow the app to open links in the default browser. There wasn't any code changes by me manually, all I did is run command `npm run tauri add shell` to add the plugin. It modified all the files itself and here we are. 

Fixes # (issue)
#85 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Idk, it wasn't opening any links for me on my ubuntu 24. Now it does open perfectly ;D
 
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules (idk what this means)

### CODE REVIEW

**Comment by Abdenasser** [comment]
thank you for taking time to fix that, really appreciate it.. let's not reformat everything.. It will be nice to only see the diff of the code responsible of opening the update.

**Review by Abdenasser — CHANGES_REQUESTED** [review]
can you please address my first comment.

**Review by Abdenasser — APPROVED** [review]

**Comment by back2Lobby** [comment]
Man you are super fast, I was just stuck in the git related things, sorry for that 😅

**Comment by Abdenasser** [comment]
> Man you are super fast, I was just stuck in the git related things, sorry for that 😅

no worried man, and thanks a lot for fixing that!

**Comment by mert-kurttutan** [comment]
@Abdenasser I was just checking if there is any redundant dependencies on the rust side. realized that tauri_plugin_shell might be one of them.
Then, checked if the error actually occurs before this fix was introduced. 
I was not able reproduce the error. Were you able to reproduce the error?

**Pull request merged**
