### PR TITLE
Rust refactor

### PR DESCRIPTION
**Pull request by Abdenasser**
## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Abdenasser** [comment]
@Pinguin2001 @andrewjanssen @nasyxx @razor950 @phillipthelen @minsusun @NoPlagiarism 
this is a big refactor + documentation for the backend side, would really appreciate it if some of you guys can try to build this locally and see if it throws any errors (I only tested this on MacOS and it is stable, but would want to double check on other systems as well) thank you all ❤️

**Comment by andrewjanssen** [comment]
> this is a big refactor + documentation for the backend side, would really appreciate it if some of you guys can try to build this locally and see if it throws any errors
Works for me, nothing seems amiss. Node 18.13, MacOS 15.1, M1.

**Comment by Abdenasser** [comment]
> > this is a big refactor + documentation for the backend side, would really appreciate it if some of you guys can try to build this locally and see if it throws any errors
> 
> Works for me, nothing seems amiss. Node 18.13, MacOS 15.1, M1.

thanks @andrewjanssen really appreciate your help 🙏🏻

**Comment by minsusun** [comment]
> this is a big refactor + documentation for the backend side, would really appreciate it if some of you guys can try to build this locally and see if it throws any errors (I only tested this on MacOS and it is stable, but would want to double check on other systems as well) thank you all ❤️

Seems no problem at all building locally

Node 20.14, MacOS 15.0.1 M1

BTW, is below glitch(?) on the title bar intended?

https://github.com/user-attachments/assets/7ff4b162-16a2-4767-ae10-b4c2f7aeac8e

**Comment by Abdenasser** [comment]
> > this is a big refactor + documentation for the backend side, would really appreciate it if some of you guys can try to build this locally and see if it throws any errors (I only tested this on MacOS and it is stable, but would want to double check on other systems as well) thank you all ❤️
> 
> Seems no problem at all building locally
> 
> Node 20.14, MacOS 15.0.1 M1
> 
> ~BTW, is below glitch(?) on the title bar intended?~
> 
> It works well on dark mode, but on light mode, animation seems a little bit awkward. Maybe I should open a new issue
> 
>  Screen.Recording.2024-11-13.at.11.09.31.AM.mov

thank you @minsusun yeah that effect is intentional, but feel free to tweak it a bit for light mode themes if you like

**Comment by NoPlagiarism** [comment]
I guess it builded, but I have some problems with Acrylic effect. Lags + incorrect size


https://github.com/user-attachments/assets/b127e3d2-7b95-40b3-b767-14178b94f6cb

**Comment by Abdenasser** [comment]
> I guess it builded, but I have some problems with Acrylic effect. Lags + incorrect size
> 
>  3QXXTDUp1c.mp4

@NoPlagiarism Acrylic effect is only supposed to work on Windows, on linux I'm disabling glassy theme and opacity effects

**Comment by NoPlagiarism** [comment]
> you should enable glassy theme from the themes menu

image

It works, but Acrylic effect is still very-very laggy for me

It would be nice to disable Acrylic (of course, it should exclude Glassy from themes)

**Comment by NoPlagiarism** [comment]
> it should exclude Glassy from themes

Just FYI, this is how Glassy looks on Windows 10 22H2 without Acrylic effect (and w/o any other modifications except removing it)

image

**Comment by Pinguin2001** [comment]
@Abdenasser I have tested it extensively and I noticed a significant improvement in startup time as well as much better structured code, great work!

**Comment by Abdenasser** [comment]
> @Abdenasser I have tested it extensively and I noticed a significant improvement in startup time as well as much better structured code, great work!

thank you, I'm also storming over a big refactor for the svelte part... will disable the effects for windows (will keep it only for macos)

**Comment by NoPlagiarism** [comment]
> will disable the effects for windows

You can try `apply_blur` for Windows 10 and `apply_mice` for Windows 11 on loading Glassy themes + `clear_blur` / `clear_mica` on all non-Glassy

**Comment by NoPlagiarism** [comment]
`apply_acrylic` vs `apply_blur`

https://github.com/user-attachments/assets/3515dd27-050c-4ecf-9598-256422cbc51d

**Comment by Abdenasser** [comment]
> `apply_acrylic` vs `apply_blur`
> 
>  GI04J6jRzZ.mp4

great, you can maybe submit a PR for that

**Comment by NoPlagiarism** [comment]
What about `apply_mica` for Windows 11? I'm not sure about me testing it, since I need VM to do it

**Pull request merged**
