### PR TITLE
fix: disk stats on windows

### PR DESCRIPTION
**Pull request by Pinguin2001**
## Description

Fixes disk stats on windows using a simple platform check

image

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I ran the app myself on windows and verified functionality

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Abdenasser** [comment]
@Pinguin2001 this is being worked on at [57](https://github.com/Abdenasser/neohtop/pull/57)

**Comment by Pinguin2001** [comment]
> @Pinguin2001 this is being worked on at [57](https://github.com/Abdenasser/neohtop/pull/57)

Yes, however, this pr is a much simpler solution keeping the original functionality of disk filtering by mount points

**Comment by Abdenasser** [comment]
> > @Pinguin2001 this is being worked on at [57](https://github.com/Abdenasser/neohtop/pull/57)
> 
> Yes, however, this pr is a much simpler solution keeping the original functionality of disk filtering by mount points

yeah it's good, thank you for taking time to work on it.. but this would only display disk stats for C drive on windows

**Comment by Pinguin2001** [comment]
> > > @Pinguin2001 this is being worked on at [57](https://github.com/Abdenasser/neohtop/pull/57)
> > 
> > 
> > Yes, however, this pr is a much simpler solution keeping the original functionality of disk filtering by mount points
> 
> yeah it's good, thank you for taking time to work on it.. but this would only display disk stats for C drive on windows

Yes that makes more sense to have it show the disk usage for all disks

**Pull request closed without merging**
